### ISSUE TITLE
Per-chat nickname support

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-facebook#11]
Messenger seems to support per-chat nicknames that are visible to everyone, which means the bridge could use those.

**Comment by NicolaiSoeborg** [comment]
This is possible using:

```yaml
bridge:
    displayname_preference:
    - nickname
    - name
```

(`example-config.yaml` with this as default has been added in https://github.com/tulir/mautrix-facebook/pull/103/)
