### ISSUE TITLE
Matrix->Facebook messages get backfilled on bridge restart 

### ISSUE THREAD

**Issue by mrjohnson22** [tulir/mautrix-facebook#138]
If I send a message in a portal room with a double-puppeted account, then restart the bridge, it will get posted again by my Facebook user puppet, as if backfilling a missed message.

My config:
```
homeserver:
    address: https://domain.tld
    domain: domain.tld
    verify_ssl: true
    asmux: false

appservice:
    address: http://localhost:29319
    hostname: ::1
    port: 29319
    max_body_size: 1
    database: postgres://synapse_user:postgres@localhost/mautrix_facebook

    database_opts:
        min_size: 5
        max_size: 10

    public:
        enabled: false
        prefix: /public
        external: https://example.com/public
        shared_secret: ...

    id: facebook
    bot_username: facebookbot
    bot_displayname: Facebook bridge bot
    bot_avatar: mxc://...
    community_id:
    ephemeral_events: true

    as_token: m7k7yofgp5r40d83iqe8rm8teyci3m5mb196feutrjp9bqw9s4kyy28afsw6ue5n
    hs_token: ksu8v2acakvnuzczqe2tkjw3tc9jrosg2ocerrpcymj1szfv95bdrprtnrfm8vvk

metrics:
    enabled: false
    listen_port: 8000

bridge:
    username_template: facebook_{userid}
    community_template: facebook_{localpart}={server}
    displayname_template: '{displayname} (FB)'
    displayname_preference:
    - name
    - first_name

    command_prefix: '!fb'
    initial_chat_sync: 3
    invite_own_puppet_to_pm: true
    sync_with_custom_puppets: false
    sync_direct_chat_list: true
    double_puppet_server_map: {}
    double_puppet_allow_discovery: false
    login_shared_secret_map: {}
    presence: true
    update_avatar_initial_sync: true

    encryption:
        allow: false
        default: false
        key_sharing:
            allow: false
            require_cross_signing: false
            require_verification: true

    delivery_receipts: true
    allow_invites: true

    backfill:
        invite_own_puppet: true
        initial_limit: 1000
        missed_limit: 1000
        disable_notifications: false

    periodic_reconnect:
        interval: 3600
        mode: refresh
        always: false

    resync_max_disconnected_time: 5
    temporary_disconnect_notices: true
    refresh_on_reconnection_fail: true
    resend_bridge_info: false

    permissions:
        domain.tld: user
        '@me:domain.tld': admin
```
