### ISSUE TITLE
Consider raising default log level from DEBUG

### ISSUE THREAD

**Issue by nivekuil** [tulir/mautrix-facebook#90]
The example config has 
```
loggers:
        mau:
            level: DEBUG
...
root:
        level: DEBUG
```
Maybe this should be INFO?
